server:
  port: ${PORT:5000}

eureka:
  instance:
    preferIpAddress: true
  server:
    enableSelfPreservation: false
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://jalgoarena-eureka.herokuapp.com/eureka/
