server:
  port: ${PORT:5000}

eureka:
  instance:
    hostname: ${APP_NAME}.herokuapp.com
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
